name: First Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Just-print:
    runs-on: ubuntu-latest
    steps:
      - name: print something
        run: echo Hey! My name is Abhishek Singh

