name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  buildx:

    runs-on: Windows

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B install --file JavaMVC/pom.xml

    - name: Download Docker installer
      run: Invoke-WebRequest -Uri 'https://download.docker.com/win/stable/InstallDocker.exe' -OutFile 'InstallDocker.exe'
    - name: Install Docker Desktop
      run: Start-Process -FilePath 'InstallDocker.exe' -ArgumentList '/quiet /norestart' -Wait -ErrorAction Stop
    - name: Login to Docker Hub (optional)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      run: docker build . --file JavaMVC/Dockerfile --tag abhisheksingh26/GitActionTryout
    - name: Run the docker image
      run: docker run -d --name gitactions -p 8084:8080 abhisheksingh26/GitActionTryout

